language: node_js
node_js:
- node
notifications:
  email: false
  slack:
    secure: G6/6IY82efMq+z/mkrsaicfBetr0X+YOrvnCK99yZJ2yc7T+dk52SvUJfggYNLaTqS6LPLxLL/USbEF6RuVML5E4/Xwn/tU67lJrrsPgUiSsselKK3WHCLUxOEnIUQ0UrxmddBAc/Zb/CH9z2KcKqIUKNMlc3FnGmcmPriG9PMGM68dNvt3LfdO8Ch5JdXl5F5g+DRjOPILCVIfDyK3Bn8cYfsWUG1kJJN9AofsPqqnnem84WDx3KMO+mN8G/N2inj8BnyU/XIukII7etqNhanuDTLYq6T6070w5FkqPY7Z6XomkUgaRk5+jgG4gMOA02stRz7PMypL9hDRPzb8vezEUPFRGO6fwSwuJlvOZs18dB3RXfCKv750E5/1iuXsPq3Sma6GZh94g7th71vLgy15Sm4jaU1hSPMPApT2sZ3EEbBv14q5w3J8s2+uNKaHYcBMQtYlM7gma6nQBSyyRfN/pptRz88oI1kJBL2ETY2CVdJuSnI6vcRJA3TuQCIYlsvCWsM/vEzrZeNeBUoUxHfnS62lkELJUA2BY+uKn7mnavlpccpz/Oc7mbCzbcd8Cg7pKis4ruSA69CURR8MfdOA/UVCBGi1p/RZdF6kXcSsgyPezSC2QtKZmar7N37uAy3rTWDc8LOoiqGPPUm/ErTEea10OHY3hBFG7vm9pGAg=
