language: node_js
node_js:
- node
notifications:
  email: false
  slack:
    rooms:
      secure: c930B9wMqOj3M/RRT+3GSXYU/T7fv+LI54h0HguIrtJA6jBqya8GpcHwszQ/CRIZ8YWuZz+hYbW0EVjOw3i5JvRLD4SVxd7T4PltgS19l4OyzGyahg47fMv6p2jVzH9BcHMHBZq2bk20l9gdDu8fnapFSMBj0DjoZA+G3ixEFAZm+5IdvGtQvzaooJttwHo/lnkZb5GldP0Rk9Z5FVH0lkPU7G6o0+OyRoTNRtWwMiiFOMNrokoVjXUeVN2XVu7DPA/cMK7PUnHzRM932fp6zOnOozBNbV3pCEUy4Lo/Ttn6zA9VzqO55BTKxSkZKQLP8rQef0n83bm705Y9NotA1p5ZCgFbjZdS7brVIdvdq8HFrq02c0LLFlKs0lmHYfhP/X7ba/y3gQ3SWl0hpwRtyFMK0Ca6xQW/ZBJVJEgr0aDo6Gg8G2lCeRs3HoAlRovE9KvoTN4WwvzGfg3qtIa37CJc9i8NQa3dc/XcJRmQuUcntxabMeMh4FMZDtG5CluaCS8+64SquRmGBj4JLqOxOhio4ez0HiUuFsPmx97wWsGszVPmJkV/gDExJ8uFHSL0xTAypf8eocoOiylKX6V+CZipUXgfOO8i+VOgKdFDwgLI1PuTO6XHpzqNrc29AbJDjBCciQJs/qcUiLC5DQ+VX0ymcRqV6kKCEkRLgNI1ttg=
